/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContUsuario;
import Logica.dtColaborador;
import Logica.dtFecha;
import Logica.dtProponente;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jp
 */
public class Alta_Perfil extends javax.swing.JInternalFrame {
 ContUsuario contUsu = ContUsuario.getInstance();
    boolean usuTipo;
    String imagenRuta = null;
    JFileChooser navegadorArchivos = new JFileChooser();
    /**
     * Creates new form Alta_Perfil
     */
    public Alta_Perfil() {
        initComponents();
   //*     686,675
        this.setSize(new Dimension(686, 675));
        jT_direccion.enable(false);
        jT_web.enable(false);
        jtp_biografia.enable(false);
        jb_aceptar.setEnabled(false);
       // this.setLocationRelativeTo(null);
        Date min = new Date("1950/01/01");
        Date max = new Date("2000/12/31");
        jdc_fechaNac.getDateEditor().setEnabled(false);
        jdc_fechaNac.setMaxSelectableDate(max);
        jdc_fechaNac.setMinSelectableDate(min);
        jP_contra.setText(null);
        jP_contraVS.setText(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_aceptar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jrb_proponente = new javax.swing.JRadioButton();
        jrb_colaborador = new javax.swing.JRadioButton();
        jb_examinar = new javax.swing.JButton();
        jL_imagenP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdc_fechaNac = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtp_biografia = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jT_direccion = new javax.swing.JTextField();
        jT_web = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jT_email = new javax.swing.JTextField();
        jT_apellido = new javax.swing.JTextField();
        jT_nombre = new javax.swing.JTextField();
        jT_nick = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jP_contra = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jP_contraVS = new javax.swing.JPasswordField();

        jb_aceptar.setText("Aceptar");
        jb_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aceptarActionPerformed(evt);
            }
        });

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });

        jrb_proponente.setText("Proponente");
        jrb_proponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_proponenteActionPerformed(evt);
            }
        });

        jrb_colaborador.setText("Colaborador");
        jrb_colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_colaboradorActionPerformed(evt);
            }
        });

        jb_examinar.setText("Examinar");
        jb_examinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_examinarActionPerformed(evt);
            }
        });

        jL_imagenP.setText("Imagen");

        jLabel6.setText("Imagen ");

        jLabel5.setText("Fecha Nacimiento");

        jtp_biografia.setColumns(20);
        jtp_biografia.setRows(5);
        jScrollPane1.setViewportView(jtp_biografia);

        jLabel9.setText("Biografia");

        jLabel7.setText("Pagina Web");

        jLabel8.setText("Direccion");

        jLabel1.setText("NickName");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Email");

        jLabel10.setText("Password");

        jP_contra.setText("jPasswordField1");

        jLabel11.setText("Confirmacion password");

        jP_contraVS.setText("jPasswordField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jb_examinar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jL_imagenP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jT_web, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(53, 53, 53)
                .addComponent(jT_email, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addComponent(jT_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(15, 15, 15)
                .addComponent(jdc_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jP_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jP_contraVS, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_colaborador)
                        .addGap(17, 17, 17)
                        .addComponent(jrb_proponente)))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jb_aceptar)
                .addGap(41, 41, 41)
                .addComponent(jb_cancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jT_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jT_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jT_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(jb_examinar)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7))
                    .addComponent(jL_imagenP, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jT_web, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(jT_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jT_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdc_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(jP_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jP_contraVS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_colaborador)
                            .addComponent(jrb_proponente)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_aceptar)
                    .addComponent(jb_cancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_examinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_examinarActionPerformed
        selecImagen();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_examinarActionPerformed

    private void jrb_colaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_colaboradorActionPerformed
        usuTipo = false;
        jb_aceptar.setEnabled(true);
        jT_direccion.disable();
        jT_web.disable();
        jtp_biografia.disable();
        jrb_proponente.setSelected(false);
        jT_web.setText("");
        jT_direccion.setText("");
        jtp_biografia.setText("");
    }//GEN-LAST:event_jrb_colaboradorActionPerformed

    private void jrb_proponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_proponenteActionPerformed
        jrb_colaborador.setSelected(false);
        usuTipo = true;
        jb_aceptar.setEnabled(true);
        jT_direccion.enable();
        jT_web.enable();
        jtp_biografia.enable();
        jrb_colaborador.setSelected(false);
    }//GEN-LAST:event_jrb_proponenteActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        limpiarTxt();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aceptarActionPerformed
        if (altaPerfil() == true) {
            JOptionPane.showMessageDialog(null, "Usuario agregado con exito");
            limpiarTxt();
        } else {
            // JOptionPane.showMessageDialog(null, "No se pudo agregar el usuario");
        }
    }//GEN-LAST:event_jb_aceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jL_imagenP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jP_contra;
    private javax.swing.JPasswordField jP_contraVS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_apellido;
    private javax.swing.JTextField jT_direccion;
    private javax.swing.JTextField jT_email;
    private javax.swing.JTextField jT_nick;
    private javax.swing.JTextField jT_nombre;
    private javax.swing.JTextField jT_web;
    private javax.swing.JButton jb_aceptar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_examinar;
    private com.toedter.calendar.JDateChooser jdc_fechaNac;
    private javax.swing.JRadioButton jrb_colaborador;
    private javax.swing.JRadioButton jrb_proponente;
    private javax.swing.JTextArea jtp_biografia;
    // End of variables declaration//GEN-END:variables
 // funciones
    private boolean controlDatos() throws Exception {

        if (jT_nick.getText() == null) {
            JOptionPane.showMessageDialog(null, "Nickname vacio");
            jT_nick.selectAll();
            jT_nick.requestFocus();
            return false;
        }
        if (contUsu.existeUsuario(jT_nick.getText())) {
            JOptionPane.showMessageDialog(null, "Ya existe un otro usuario con este nickname");
            jT_nick.selectAll();
            jT_nick.requestFocus();
            return false;
        }
        if (jP_contra.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una contraseña");
            jP_contra.selectAll();
            jP_contra.requestFocus();
            return false;
        }
        if (jP_contraVS.getText() == null) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la confirmacion de la contraseña");
            jP_contraVS.selectAll();
            jP_contraVS.requestFocus();
            return false;
        }

        if (jP_contra.getText().equals(jP_contraVS.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Contraseñas diferentes!");
            jP_contra.selectAll();
            jP_contra.requestFocus();
            return false;
        }
        if (jT_nombre.getText() == null) {
            JOptionPane.showMessageDialog(null, "Nombre vacio");
            jT_nombre.selectAll();
            jT_nombre.requestFocus();
            return false;
        }
        if (jT_apellido.getText() == null) {
            JOptionPane.showMessageDialog(null, "Apellido vacio");
            jT_apellido.selectAll();
            jT_apellido.requestFocus();
            return false;
        }
        if (jT_email.getText() == null) {
            JOptionPane.showMessageDialog(null, "Email vacio");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (compruebaEmail(jT_email.getText()) != true) {
            JOptionPane.showMessageDialog(null, "Email incorrecto");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (contUsu.existeMail(jT_email.getText())) {
            JOptionPane.showMessageDialog(null, "Ya existe otro usuario registrado con este mail");
            jT_email.selectAll();
            jT_email.requestFocus();
            return false;
        }
        if (jdc_fechaNac == null) {
            JOptionPane.showMessageDialog(null, "Fecha nacimiento vacia");
            jdc_fechaNac.requestFocus();
            return false;
        }
        return true;
    }

    private boolean fechaok() {
        int dia = 0, mes = 0, anio = 0;
        dia = jdc_fechaNac.getDate().getDay();
        mes = jdc_fechaNac.getDate().getMonth();
        anio = jdc_fechaNac.getDate().getYear();

        int Cdia = 01, cMes = 01, Canio = 1945;
        if (dia == Cdia) {
            if (mes == cMes) {
                if (anio == Canio) {
                    return true;
                }
            }
        }
        return false;
    }

    private dtFecha getFechajdc() {
        dtFecha fecha;
        fecha = new dtFecha(Integer.toString(jdc_fechaNac.getDate().getDay()), Integer.toString(jdc_fechaNac.getDate().getMonth()), Integer.toString(jdc_fechaNac.getDate().getYear()));
        return fecha;
    }

    private boolean compruebaEmail(String email) {
        // Patrón para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);

        return mather.find();
    }

    private void limpiarTxt() {
        jT_nick.setText(null);
        jT_nombre.setText(null);
        jT_apellido.setText(null);
        jT_email.setText(null);
        jdc_fechaNac.setCalendar(null);
        jT_direccion.setText(null);
        jT_web.setText(null);
        jtp_biografia.setText(null);
        jrb_colaborador.setSelected(false);
        jrb_proponente.setSelected(false);
        jT_direccion.disable();
        jT_web.disable();
        jtp_biografia.disable();
        jb_aceptar.disable();
        jL_imagenP.setIcon(null);
        jP_contra.setText(null);
        jP_contraVS.setText(null);
        jb_aceptar.setEnabled(false);
    }

    private boolean altaPerfil() {

        try {

            if (controlDatos() == true) {

                if (usuTipo == false) {

                    dtColaborador dtCola = new dtColaborador((jT_nombre.getText()), jT_apellido.getText(), jT_nick.getText(),
                            imagenRuta, jT_email.getText(), getFechajdc(), jP_contra.getText());
                    contUsu.agregarUsu(dtCola);
                    return true;
                }

                if (usuTipo == true) {
                    dtProponente dtprop = new dtProponente(jT_nombre.getText(), jT_apellido.getText(), jT_nick.getText(), imagenRuta, jT_email.getText(), getFechajdc(), jT_direccion.getText(), jtp_biografia.getText(), jT_web.getText(), jP_contra.getText());
                    contUsu.agregarUsu(dtprop);
                    return true;
                }

            } else {
                return false;
            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        return false;

    }

    private void selecImagen() {
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        navegadorArchivos.setFileFilter(filtroImagen);
        navegadorArchivos.showOpenDialog(this);
        File imagen = navegadorArchivos.getSelectedFile();
        String path = navegadorArchivos.getSelectedFile().getPath();
        jL_imagenP.setIcon(new ImageIcon(path));
        ImageIcon icon = new ImageIcon(path);
        Image foto = icon.getImage();
        Image nuevaFoto = foto.getScaledInstance(jL_imagenP.getWidth(), jL_imagenP.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon nuevoIcono = new ImageIcon(nuevaFoto);
        jL_imagenP.setIcon(nuevoIcono);
        //BufferedImage img= nuevoIcono;
        salvarImagen(nuevaFoto);
    }

    private void salvarImagen(Image imagen) {
        BufferedImage img = (BufferedImage) imagen;
        File outputfile = new File(contUsu.getImagenDestino() + jT_nick.getText() + ".png");
        imagenRuta =  jT_nick.getText() + ".png";
        try {
            ImageIO.write(img, "png", outputfile);
        } catch (IOException ex) {
            System.err.println(ex.getMessage());

        }

    }

}
