/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContPropuesta;
import Logica.ContUsuario;
import Logica.dtFecha;
import Logica.dtHora;
import Logica.dtPropuesta;
import Logica.utilidades;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolasgutierrez
 */
public class Modificar_datos_de_Propuesta extends javax.swing.JInternalFrame {

    ContUsuario contUsu = ContUsuario.getInstance();
    ContPropuesta contProp = ContPropuesta.getInstance();
    String imagenRuta = "COSO";
    JFileChooser navegadorArchivos = new JFileChooser();
    utilidades util = utilidades.getInstance();

    /**
     * Creates new form Modificar_datos_de_Propuesta
     */
    private String rearmarFecha(String f) {
        String fecha = null;
        String[] a = f.split("/");
        fecha = a[2] + "/" + a[1] + "/" + a[0];
        return fecha;
    }

    public Modificar_datos_de_Propuesta() {
       try {
            
            initComponents();
            contProp.propAutomaticas();
            this.setSize(900, 700);
            jLabel1.setText("Propuestas");
            jLabel13.setText("Titulo");
            labeltitulo.setText("Seleccione una propuesta");
            jLabel14.setText("Proponente");
            labelproponente.setText("Seleccione una propuesta");
            jLabel2.setText("Descripcion");
            jLabel3.setText("Lugar");
            jLabel4.setText("Imagen");
            btnexplorar2.setText("Explorar");
            jLabel5.setText("Fecha realizacion");
            jLabel11.setText("Estado");
            jLabel9.setText("Precio entrada");
            jLabel10.setText("Monto requerido");
            jLabel12.setText("Categoria");
            labelcategoria.setText("Seleccione una propuesta");
            jLabel15.setText("Fecha publicacion");
            lRe.setText("Retorno");
            labelretorno.setText("Seleccione una propuesta");
            btncancelar.setText("Cancelar");
            btnguardar.setText("Guardar");
            txtestado.setEditable(false);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        labelretorno = new javax.swing.JLabel();
        lRe = new javax.swing.JLabel();
        fechaPublicada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelcategoria = new javax.swing.JLabel();
        labelproponente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        busquedapropuestas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnexplorar2 = new javax.swing.JButton();
        txtmontorequerido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        labelimage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtlugar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jd_fechaRealizacion = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtprecioetrada = new javax.swing.JTextField();

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        labelretorno.setText("jLabel6");

        lRe.setText("jLabel6");

        jLabel15.setText("Fecha publicacion");

        jLabel12.setText("Categoria");

        labelcategoria.setText("Seleccione una propuesta");

        labelproponente.setText("Seleccione una propuesta");

        jLabel14.setText("Proponente");

        labeltitulo.setText("Seleccione una propuesta");

        jLabel13.setText("Titulo");

        txtdescripcion.setColumns(20);
        txtdescripcion.setRows(5);
        jScrollPane2.setViewportView(txtdescripcion);

        jLabel2.setText("Descripcion");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Titulo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        busquedapropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedapropuestasActionPerformed(evt);
            }
        });
        busquedapropuestas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busquedapropuestasKeyPressed(evt);
            }
        });

        jLabel1.setText("Propuestas");

        btnexplorar2.setText("Explorar");
        btnexplorar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexplorar2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Monto requerido");

        labelimage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 0)));

        jLabel4.setText("Imagen");

        jLabel3.setText("Lugar");

        jLabel5.setText("Fecha realizacion");

        jLabel11.setText("Estado");

        jLabel9.setText("Precio entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtlugar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnexplorar2)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(busquedapropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jd_fechaRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtprecioetrada, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtmontorequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(87, 87, 87)
                .addComponent(labelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addComponent(labeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel14)
                .addGap(36, 36, 36)
                .addComponent(labelproponente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel12)
                .addGap(20, 20, 20)
                .addComponent(labelcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(14, 14, 14)
                        .addComponent(fechaPublicada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lRe)
                        .addGap(29, 29, 29)
                        .addComponent(labelretorno)))
                .addGap(290, 290, 290)
                .addComponent(btnguardar)
                .addGap(18, 18, 18)
                .addComponent(btncancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(txtlugar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnexplorar2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(busquedapropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(jd_fechaRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11)
                        .addGap(5, 5, 5)
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(txtprecioetrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(5, 5, 5)
                        .addComponent(txtmontorequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(labelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(labeltitulo))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(labelproponente))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(labelcategoria))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15))
                            .addComponent(fechaPublicada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lRe)
                            .addComponent(labelretorno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedapropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedapropuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedapropuestasActionPerformed

    private void busquedapropuestasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedapropuestasKeyPressed
        List<String> proponentes = contUsu.listartodaslaspropuestas(busquedapropuestas.getText());
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (int i = 0; i < proponentes.size(); i++) {
            String p = proponentes.get(i);
            Object[] dat = {p};
            modelo.addRow(dat);
        }


    }//GEN-LAST:event_busquedapropuestasKeyPressed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            int row = jTable1.rowAtPoint(evt.getPoint());
            int col = jTable1.columnAtPoint(evt.getPoint());
            dtPropuesta dtp;
            dtp = contUsu.infoPropuesta((String) jTable1.getValueAt(row, col));
            txtdescripcion.setText(dtp.getDescripcion());
            txtlugar.setText(dtp.getLugar());
            txtprecioetrada.setText(Integer.toString(dtp.getPrecioentrada()));
            txtmontorequerido.setText(Integer.toString(dtp.getMontorequerido()));
            txtestado.setText(dtp.getEstado());
            labeltitulo.setText(dtp.getTitulo());
            labelproponente.setText(dtp.getProponente());
            imagenRuta = dtp.getImagen();
            labelcategoria.setText(dtp.getCategoria());
            String fecha = (String) util.getFecha().getFecha();
            Date min = new Date(rearmarFecha((String) util.getFechaInc(fecha, null, 1)));
            jd_fechaRealizacion.setMinSelectableDate(min);
            jd_fechaRealizacion.setDate((Date) utilidades.fechaDate(dtp.getFechaRealizacion().getFecha(), null));
            fechaPublicada.setText(dtp.getFechapublicada().getFecha());
            fechaPublicada.setEditable(false);
            labelretorno.setText(dtp.getRetorno());

        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        try {
            dtFecha fechaP = util.construirFecha(fechaPublicada.getText());
            dtPropuesta dtp = new dtPropuesta(labeltitulo.getText(), txtdescripcion.getText(), imagenRuta, txtlugar.getText(), txtestado.getText(), labelcategoria.getText(), labelproponente.getText(), (dtFecha) getFechajdcRealizacion(), fechaP, Integer.parseInt(txtprecioetrada.getText()), Integer.parseInt(txtmontorequerido.getText()), 0, labelretorno.getText());
            contProp.actualizardatospropuesta(dtp, txtestado.getText(), (dtFecha) util.getFecha(), (dtHora) util.getHora());
            JOptionPane.showMessageDialog(null, "Propuesta modificada con exito");
            sacarlabasura();
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnexplorar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexplorar2ActionPerformed
        // TODO add your handling code here:
        selecImagen();
    }//GEN-LAST:event_btnexplorar2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnexplorar2;
    private javax.swing.JButton btnguardar;
    private javax.swing.JTextField busquedapropuestas;
    private javax.swing.JTextField fechaPublicada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser jd_fechaRealizacion;
    private javax.swing.JLabel lRe;
    private javax.swing.JLabel labelcategoria;
    private javax.swing.JLabel labelimage;
    private javax.swing.JLabel labelproponente;
    private javax.swing.JLabel labelretorno;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JTextArea txtdescripcion;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtlugar;
    private javax.swing.JTextField txtmontorequerido;
    private javax.swing.JTextField txtprecioetrada;
    // End of variables declaration//GEN-END:variables

    private void selecImagen() {
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        navegadorArchivos.setFileFilter(filtroImagen);
        navegadorArchivos.showOpenDialog(this);
        File imagen = navegadorArchivos.getSelectedFile();
        String path = navegadorArchivos.getSelectedFile().getPath();
        labelimage.setIcon(new ImageIcon(path));
        ImageIcon icon = new ImageIcon(path);
        Image foto = icon.getImage();
        Image nuevaFoto = foto.getScaledInstance(labelimage.getWidth(), labelimage.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon nuevoIcono = new ImageIcon(nuevaFoto);
        labelimage.setIcon(nuevoIcono);
        //BufferedImage img= nuevoIcono;
        salvarImagen(foto);
    }

    private void salvarImagen(Image imagen) {
        BufferedImage img = (BufferedImage) imagen;
        File outputfile = new File("/home/juan/ProgAplicaciones2018/progAplicaciones/imagenesPropuesta" + labeltitulo.getText() + ".png");
        imagenRuta = "/home/juan/ProgAplicaciones2018/progAplicaciones/imagenesPropuesta" + labeltitulo.getText() + ".png";
        try {
            ImageIO.write(img, "png", outputfile);
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
    }

    private void sacarlabasura() {
        labeltitulo.setText("Seleccione una propuesta");
        labelproponente.setText("Seleccione una propuesta");
        labelcategoria.setText("Seleccione una propuesta");
        labelretorno.setText("Seleccione una propuesta");
        txtdescripcion.setText(null);
        txtlugar.setText(null);
        txtestado.setText(null);
        txtprecioetrada.setText(null);
        txtmontorequerido.setText(null);
        jd_fechaRealizacion.setCalendar(null);
    }

    private dtFecha getFechajdcRealizacion() {

        dtFecha fecha;
        System.out.println(jd_fechaRealizacion.getCalendar().get(Calendar.MONTH));
        fecha = new dtFecha(Integer.toString(jd_fechaRealizacion.getCalendar().get(Calendar.DAY_OF_WEEK)), Integer.toString(jd_fechaRealizacion.getCalendar().get(Calendar.MONTH) + 1), Integer.toString(jd_fechaRealizacion.getCalendar().get(Calendar.YEAR)));
        return fecha;

    }
}
