/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ContColaboracion;
import Logica.ContPropuesta;
import Logica.ContUsuario;
import Logica.dtColaborador;
import Logica.dtFecha;
import Logica.dtHora;
import Logica.dtProponente;
import Logica.dtPropuesta;
import Logica.dtUsuario;
import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nicolasgutierrez
 */
public class Registrar_Colaboracion_a_Propuesta extends javax.swing.JInternalFrame {

    ContUsuario contUsu = ContUsuario.getInstance();
    ContPropuesta contProp = ContPropuesta.getInstance();
    int maxmonto;

    /**
     * Creates new form Registrar_Colaboracion_a_Propuesta
     */
    public Registrar_Colaboracion_a_Propuesta() {
        initComponents();
        contProp.propAutomaticas();
        this.setSize(1000, 800);
        //String titulo[]={"nickName"};
        // llenarGrilla(jTable_proponente, titulo, proponentes);

        jLabel1.setText("Propuestas");
        jLabel5.setText("Monto total recaudado");
        jLabel3.setText("Estado");
        jLabel2.setText("Colaboradores");
        jLabel8.setText("Propuesta");
        jLabel4.setText("Colaborador");
        txtnickcolaborador.setEditable(false);
        txttituloprop.setEditable(false);
        jLabel6.setText("Tipo de retorno");
        jLabel7.setText("Monto");
        btnaceptar.setText("Aceptar");
        btncancelar.setText("Cancelar");
        cbporcentaje.setText("Porcentaje");
        cbentradas.setText("Entrada");
        jTA_comentario.setEditable(false);
        txtmontotoal.setEditable(false);
        btnaceptar.setEnabled(false);
        txtmontoacolaborar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tpropuestas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_propuestas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtmontotoal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablecolaboradores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablecolaborador = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmontoacolaborar = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        busquedapropuestas = new javax.swing.JTextField();
        cbporcentaje = new javax.swing.JCheckBox();
        cbentradas = new javax.swing.JCheckBox();
        busuqedacolaboradores = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTA_comentario = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txttituloprop = new javax.swing.JTextField();
        txtnickcolaborador = new javax.swing.JTextField();

        tpropuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Titulo"
            }
        ));
        tpropuestas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpropuestasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tpropuestas);

        jLabel1.setText("Propuestas");

        jTable_propuestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Descripcion", "Lugar", "Fecha", "Precio entrada", "Monto requerido"
            }
        ));
        jScrollPane2.setViewportView(jTable_propuestas);

        jLabel5.setText("Monto total recaudado");

        jLabel3.setText("Estado");

        txtestado.setEditable(false);
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });

        tablecolaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nickname"
            }
        ));
        tablecolaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecolaboradoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablecolaboradoresMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tablecolaboradores);

        jLabel2.setText("  Colaboradores");

        tablecolaborador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Email"
            }
        ));
        jScrollPane4.setViewportView(tablecolaborador);

        jLabel4.setText("Colaborador");

        jLabel6.setText("Tipo de retorno");

        jLabel7.setText("Monto");

        txtmontoacolaborar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmontoacolaborarActionPerformed(evt);
            }
        });
        txtmontoacolaborar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontoacolaborarKeyTyped(evt);
            }
        });

        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        busquedapropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedapropuestasActionPerformed(evt);
            }
        });
        busquedapropuestas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busquedapropuestasKeyPressed(evt);
            }
        });

        cbporcentaje.setText("Procentaje");

        cbentradas.setText("Entrada");

        busuqedacolaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busuqedacolaboradoresActionPerformed(evt);
            }
        });
        busuqedacolaboradores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                busuqedacolaboradoresKeyPressed(evt);
            }
        });

        jLabel8.setText("Propuesta");

        jTA_comentario.setColumns(20);
        jTA_comentario.setRows(5);
        jScrollPane5.setViewportView(jTA_comentario);

        jLabel9.setText("Comentario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(busquedapropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(busuqedacolaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnickcolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel7)
                                        .addGap(5, 5, 5)
                                        .addComponent(txtmontoacolaborar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtmontotoal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttituloprop, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbentradas)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbporcentaje))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel6)
                                                .addGap(46, 46, 46)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(busquedapropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(busuqedacolaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbentradas)
                                            .addComponent(cbporcentaje)))
                                    .addComponent(txttituloprop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7))
                                    .addComponent(txtmontoacolaborar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addComponent(txtmontotoal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(txtnickcolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(btnaceptar)
                        .addGap(5, 5, 5)
                        .addComponent(btncancelar))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedapropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedapropuestasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedapropuestasActionPerformed

    private void busquedapropuestasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedapropuestasKeyPressed
        List<String> proponentes = contUsu.listartodaslaspropuestas(busquedapropuestas.getText());
        DefaultTableModel modelo = (DefaultTableModel) tpropuestas.getModel();
        modelo.setRowCount(0);
        for (int i = 0; i < proponentes.size(); i++) {
            String p = proponentes.get(i);
            Object[] dat = {p};
            modelo.addRow(dat);
        }
    }//GEN-LAST:event_busquedapropuestasKeyPressed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tpropuestas.getModel();
        modelo.setRowCount(0);

        DefaultTableModel modelo2 = (DefaultTableModel) jTable_propuestas.getModel();
        modelo2.setRowCount(0);

        DefaultTableModel modelo3 = (DefaultTableModel) tablecolaboradores.getModel();
        modelo3.setRowCount(0);

        DefaultTableModel modelo4 = (DefaultTableModel) tablecolaborador.getModel();
        modelo4.setRowCount(0);

        txtmontotoal.setText("");
        txtestado.setText("");
        txtnickcolaborador.setText("Seleccione uno");

        cbentradas.setSelected(false);
        cbporcentaje.setSelected(false);
        maxmonto = 0;
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void busuqedacolaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busuqedacolaboradoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busuqedacolaboradoresActionPerformed

    private void busuqedacolaboradoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busuqedacolaboradoresKeyPressed
        // TODO add your handling code here:

        List<String> colaboradores = contUsu.listarColaboradoresLike(busuqedacolaboradores.getText());
        DefaultTableModel modelo = (DefaultTableModel) tablecolaboradores.getModel();
        modelo.setRowCount(0);
        for (int i = 0; i < colaboradores.size(); i++) {
            String c = colaboradores.get(i);
            Object[] dat = {c};
            modelo.addRow(dat);
        }

    }//GEN-LAST:event_busuqedacolaboradoresKeyPressed
    private void habilitado(String estado, String colaborador, String propuestaTitulo) {

        if (estado.equals("Financiada")) {
            if (contUsu.colaborasConPropuesta(propuestaTitulo, colaborador)) {
                jTA_comentario.setEditable(true);
                btnaceptar.setEnabled(true);
                cbentradas.setEnabled(false);
                cbporcentaje.setEnabled(false);
            }
        }
        if (controlEstado()) {
            btnaceptar.setEnabled(true);

        }
    }

    private boolean bloquear() {
        if (!controlEstado()) {
            txtmontoacolaborar.setEditable(false);
            btnaceptar.setEnabled(false);
            cbentradas.setEnabled(false);
            cbporcentaje.setEnabled(false);
            return false;
        }
        if (controlEstado()) {
                     return true;
        }
        return true;
    }
    private void tpropuestasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpropuestasMouseClicked
        // TODO add your handling code here:
        try {
            limpiarlabasura();
            int row = tpropuestas.rowAtPoint(evt.getPoint());
            int col = tpropuestas.columnAtPoint(evt.getPoint());
            dtPropuesta dtp;
            dtp = contUsu.infoPropuesta((String) tpropuestas.getValueAt(row, col));
            DefaultTableModel modelo = (DefaultTableModel) jTable_propuestas.getModel();
            modelo.setRowCount(0);
            Object[] dat = {dtp.getTitulo(), dtp.getDescripcion(), dtp.getLugar(), dtp.getFechaRealizacion().getFecha(), dtp.getPrecioentrada(), dtp.getMontorequerido()};
            txtmontotoal.setText(Integer.toString(dtp.getMontoTotal()));
            txtestado.setText(dtp.getEstado());
            txttituloprop.setText(dtp.getTitulo());
            modelo.addRow(dat);
            cbentradas.setEnabled(false);
            cbporcentaje.setEnabled(false);
            if (bloquear()) {
                if (dtp.getRetorno().contentEquals("Entrada")) {
                    cbentradas.setEnabled(true);
                }
                if (dtp.getRetorno().contentEquals("Porcentaje")) {
                    cbporcentaje.setEnabled(true);
                }
                if (dtp.getRetorno().contentEquals("Entrada/Porcentaje")) {
                    cbporcentaje.setEnabled(true);
                    cbentradas.setEnabled(true);
                }
            }
            txtnickcolaborador.setText(null);
            maxmonto = dtp.getMontorequerido() - dtp.getMontoTotal();
        } catch (Exception ex) {
            Logger.getLogger(Registrar_Colaboracion_a_Propuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tpropuestasMouseClicked

    private void tablecolaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecolaboradoresMouseClicked

        int row = tablecolaboradores.rowAtPoint(evt.getPoint());
        int col = tablecolaboradores.columnAtPoint(evt.getPoint());
        dtUsuario dtc;
        dtc = contUsu.infoColaborador((String) tablecolaboradores.getValueAt(row, col));
        DefaultTableModel modelo = (DefaultTableModel) tablecolaborador.getModel();
        modelo.setRowCount(0);
        Object[] dat = {dtc.getNombre(), dtc.getApellido(), dtc.getEmail()};
        modelo.addRow(dat);
        txtnickcolaborador.setText(dtc.getNickname());
        if(controlEstado()){txtmontoacolaborar.setEditable(true);}
        habilitado(txtestado.getText(), txtnickcolaborador.getText(), txttituloprop.getText());
    }//GEN-LAST:event_tablecolaboradoresMouseClicked
    private dtFecha getFecha() {
        dtFecha fecha = null;
        Calendar cal = Calendar.getInstance();
        Date da = cal.getTime();
        da.setYear(2018);
        fecha = new dtFecha(Integer.toString(da.getDay()), Integer.toString(da.getMonth()), Integer.toString(da.getYear()));
        return fecha;
    }

    private dtHora getHora() {
        dtHora hora = null;
        Calendar cal = Calendar.getInstance();
        Date da = cal.getTime();
        da.setYear(2018);
        hora = new dtHora(da.getHours(), da.getMinutes());
        return hora;
    }

    private String getPorcentaje() {
        String re = null;

        if (cbentradas.isSelected() && !cbporcentaje.isSelected()) {
            re = cbentradas.getText();
        } else if (cbentradas.isSelected() && cbporcentaje.isSelected()) {
            re = cbentradas.getText() + "/" + cbporcentaje.getText();
        } else if (!cbentradas.isSelected() && cbporcentaje.isSelected()) {
            re = cbporcentaje.getText();
        }
        return re;
    }

    private boolean controlEstado() {
        if (txtestado.getText().equals("Publicada")) {
            return true;
        }
        if (txtestado.getText().equals("En financiacion")) {
            return true;
        }
        return false;
    }

    private boolean controlDatos() {
        if (txtmontoacolaborar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto!");
            txtmontoacolaborar.requestFocus();
            txtmontoacolaborar.selectAll();
            return false;
        }
        if (txttituloprop.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Seleccione una propuesta");
            jTable_propuestas.requestFocus(true);
            return false;
        }
        if (txtnickcolaborador.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un colaborador!");
            tablecolaboradores.requestFocus();
            return false;
        }
        if (getPorcentaje() == null) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un retorno");
            cbporcentaje.requestFocus();
            cbentradas.requestFocus();
            return false;
        }
        return true;
    }

    private void colaborar() {
        if (controlEstado() && !txtestado.getText().equals("Financiada")) {

            if (controlDatos()) {
                int calculo = Integer.parseInt(txtmontotoal.getText());
                int cantCola = Integer.parseInt(txtmontoacolaborar.getText());

                if (cantCola <= maxmonto) {
                    String re = getPorcentaje();
                    dtFecha dtf = getFecha();
                    dtHora dth = getHora();
                    boolean b = contUsu.registrarColaboracion(txttituloprop.getText(), txtnickcolaborador.getText(), Integer.parseInt(txtmontoacolaborar.getText()), re);
                    if (txtestado.getText().equals("Publicada") && b) {
                        contProp.agregarEstadoAPropuesta("En financiacion", txttituloprop.getText(), dtf, dth);
                    }
                    int montoacolaborar = Integer.parseInt(txtmontoacolaborar.getText());
                    int montototal = Integer.parseInt(txtmontotoal.getText());
                    if (txtestado.getText().equals("En financiacion") && (maxmonto - montoacolaborar) == 0 && b) {
                        contProp.agregarEstadoAPropuesta("Financiada", txttituloprop.getText(), dtf, dth);
                    }

                    if (txtestado.getText().contains("Publicada") && (maxmonto - montoacolaborar) == 0 && b) {
                        contProp.agregarEstadoAPropuesta("Financiada", txttituloprop.getText(), dtf, dth);
                    }

                    if (b) {
                        JOptionPane.showMessageDialog(null, "Colaboracion registrada");
                        limpiarlabasura();
                    } else {
                        JOptionPane.showMessageDialog(this, "No es posible registrar la colaboracion...");
                        limpiarlabasura();
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "El monto de colaboracion es superior al necesario por la propuesta, maximo posible: " + maxmonto);
                    txtmontoacolaborar.selectAll();
                    txtmontoacolaborar.requestFocus();
                }
            }
        }
        if (txtestado.getText().equals("Financiada")) {
            if (contUsu.colaborasConPropuesta(txttituloprop.getText(), txtnickcolaborador.getText())) {
                if (!jTA_comentario.getText().isEmpty()) {
                    if (ContPropuesta.getInstance().agregarcomentarioapropuesta(txtnickcolaborador.getText(), txttituloprop.getText(), jTA_comentario.getText())) {
                        JOptionPane.showMessageDialog(this, "Se ha agregado su comentario con exit!");
                        limpiarlabasura();
                    } else {
                        JOptionPane.showMessageDialog(this, "No se pudo registrar el comentario!");
                        limpiarlabasura();
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Si lo desea puede comentar la propuesta financiada...");
                    jTA_comentario.requestFocus();
                }
            }

        }
    }

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here:
        colaborar();


    }//GEN-LAST:event_btnaceptarActionPerformed

    private void txtmontoacolaborarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmontoacolaborarActionPerformed

    }//GEN-LAST:event_txtmontoacolaborarActionPerformed

    private void txtmontoacolaborarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoacolaborarKeyTyped
        char caracter = evt.getKeyChar();
        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txtmontoacolaborarKeyTyped

    private void tablecolaboradoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecolaboradoresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablecolaboradoresMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JTextField busquedapropuestas;
    private javax.swing.JTextField busuqedacolaboradores;
    private javax.swing.JCheckBox cbentradas;
    private javax.swing.JCheckBox cbporcentaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTA_comentario;
    private javax.swing.JTable jTable_propuestas;
    private javax.swing.JTable tablecolaborador;
    private javax.swing.JTable tablecolaboradores;
    private javax.swing.JTable tpropuestas;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtmontoacolaborar;
    private javax.swing.JTextField txtmontotoal;
    private javax.swing.JTextField txtnickcolaborador;
    private javax.swing.JTextField txttituloprop;
    // End of variables declaration//GEN-END:variables

// funciones
    private void llenarGrilla(JTable tabla, String titulo[], List<String> atributos) {
        // 
        Object[] fila = new Object[titulo.length];
        DefaultTableModel modelo = new DefaultTableModel(null, titulo);
        for (int i = 0; i < atributos.size(); i++) {
            String p = atributos.get(i);
            Object[] dat = {p};
            modelo.addRow(dat);
        }
        tabla.setModel(modelo);
    }

    private static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    private void limpiarlabasura() {
        DefaultTableModel modelo = (DefaultTableModel) jTable_propuestas.getModel();
        modelo.setRowCount(0);

        DefaultTableModel modelo2 = (DefaultTableModel) tablecolaboradores.getModel();
        modelo2.setRowCount(0);

        DefaultTableModel modelo3 = (DefaultTableModel) tablecolaborador.getModel();
        modelo3.setRowCount(0);

        cbporcentaje.setSelected(false);
        cbentradas.setSelected(false);
        txtmontotoal.setText(null);
        busuqedacolaboradores.setText(null);
        txtestado.setText(null);
        txtmontoacolaborar.setText(null);
        txttituloprop.setText(null);
        txtnickcolaborador.setText(null);
        btnaceptar.setEnabled(false);
        jTA_comentario.setText(null);
    }

}
